[".config/GIMP/3.0/plug-ins"]
    type = "git-repo"
    url = "https://github.com/kai-bruell/gimp-plugins.git"
    refreshPeriod = "168h"
    clone.args = ["--recurse-submodules"]
    pull.args = ["--recurse-submodules"]
